### ISSUE TITLE
Package update and dirty DiffEqTutorials and DiffEqDocs

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqTutorials.jl#1]
Although the git stash method has been advocated to solve this issue, it would be good to have the Pkg.update() working on all JuliaDiffEq packages.

Also what is the best way to download a Jupyter notebook from a DiffEqDocs Markdown/html page? For me, it is this step which dirties the packages.

**Comment by ChrisRackauckas** [comment]
Here's a thread on it if you want to chime in:

https://discourse.julialang.org/t/whats-a-user-friendly-way-to-setup-repositories-for-jupyter-notebook-tutorials/532

**Comment by finmod** [comment]
Read all threads. For now, my preferred solution is to Pkg.rm("DiffEqTutorials") and Pkg.rm("DiffEqDocs"), the Pkg.update() to eliminate all dirty packages in connection with DifferentialEquations.

Locally, I created a JuliaDiffEQ folder with two subfolders: DiffEqTutorials and DiffEqDocs. They can be overwritten at any time leaving Jupyter notebooks in place. I will continue to create and debug the notebooks corresponding to the md files. 

They are available to you or anyone else for reuse when I will be fluent in push requests.

**Comment by ChrisRackauckas** [comment]
I don't think there is a fix for this since it's not even a Julia issue, it's a Git issue. The best solution is to `rm` or to `git stash` when the notebooks change.
