### ISSUE TITLE
problem with animation

### ISSUE THREAD

**Issue by francispoulin** [JuliaDiffEq/DiffEqTutorials.jl#12]
Sorry for bothering you with this but I am trying to put together a notebook that animates the solution to the diffusion equation.  The code below works well for plotting slices but the animation seems to go on and on and never make an animation.

Any suggestions as to what I'm doing wrong?

Needless to say, I am happy to share the notebook in case anyone might find it helpful.

```
# Import packages
using DiffEqOperators, DifferentialEquations, Plots

x = collect(-pi : 2pi/511 : pi);
u0 = -(x - 0.5).^2 + 1/12;
A = DerivativeOperator{Float64}(2,2,2pi/511,512,:Dirichlet,:Dirichlet;BC=(u0[1],u0[end]));

prob1 = ODEProblem(A, u0, (0.,10.));
sol1 = solve(prob1, dense=false, tstops=0:0.01:0.1);
    
# try to plot the solution at different time points using
plot(x, [sol1(i) for i in 0:1:10])

animate(sol1,"tmp.gif")

```

**Comment by ChrisRackauckas** [comment]
Which plotting backend are you using? I think the PyPlot backend was used for the animations.

**Comment by francispoulin** [comment]
I am not sure how to check what backend I am using. 

But in the FEM example for the Diffusion equation it uses Plots, which is what I am trying to do.  I am using what I think is the same syntax but it seems to take forever, a sign I am doing something wrong.

**Comment by francispoulin** [comment]
Some progress.

I copied another example and figured out how to make a gif.  It's step in the right direction but is it possible to have this plot the entire solution instead of just the first 10? When I look at the size of the solution it says there are 75444 or so, which seems large but I would guess there are more than 10.

```

p = plot(x,sol1(1), title="Simple Animation",label=["x" "y"],lw=3)

@gif for i in range(1,1,10)
    
    plot(x, sol1(i), xlims=(0,3), ylims=(-10,0), title="Simple Animation",label=["x" "y"],lw=3)
end
```

**Comment by ChrisRackauckas** [comment]
Sorry, I was travelling for quite awhile and now I'm back. I'll look at this ASAP but there's a backlog.

**Comment by francispoulin** [comment]
Whenever you have time.  I am sure there is an elegant way of doing this but I'm still not sure.   Sorry for not figuring it out myself.

**Comment by ChrisRackauckas** [comment]
You can do:

```julia
@gif for s in sol
    plot(s, xlims=(0,3), ylims=(-10,0), title="Simple Animation",label=["x" "y"],lw=3)
end
```

or what not. That's what `animate` is doing anyways.

But are you sure its a problem with the DiffEq animation and not an issue with your Plots.jl setup? I just ran the animation and got a a convert error, but it built the pieces just fine (this is just a Windows bug from Plots.jl).

**Comment by francispoulin** [comment]
Thanks.  That is the syntax I was looking for.  One problem is that the solution that comes out has 75,444 time steps.  If I wanted to plot the solution every 100 is there a simple way to modify the above syntax?

**Comment by ChrisRackauckas** [comment]
http://docs.juliadiffeq.org/latest/basics/plot.html#Animations-1

`every=100`.

**Comment by francispoulin** [comment]
Thank you for the suggestion.  I guess the two possibilities are either to use git or animate. I would be happy with either.  One problem is that the solution seems to have 75,444 time steps and neither of the two options seems to work.  Could it be that the solution is too big for this example?

**Comment by ChrisRackauckas** [comment]
it should work with animate? The notebook shows that.

**Comment by francispoulin** [comment]
I tried the following in a notebook and all goes well up until the end where it seems to take forever wtih animate and I have not seen it figure.  Did you actually see the result within a minute?  If you do and I don't then I think there is a problem on my end.

Again, sorry that I am having so much trouble with this.

```
# Import packages

using DiffEqOperators, DifferentialEquations, Plots

x = collect(-pi : 2pi/511 : pi);
u0 = -(x - 0.5).^2 + 1/12;
A = DerivativeOperator{Float64}(2,2,2pi/511,512,:Dirichlet,:Dirichlet;BC=(u0[1],u0[end]));

prob1 = ODEProblem(A, u0, (0.,10.));
sol1 = solve(prob1, dense=false, tstops=0:0.01:0.02);

animate(sol1,lw=3,every=10)

```

**Comment by ChrisRackauckas** [comment]
No, it takes awhile because Plots.jl currently doesn't plug directly into the fast animation setups that some backends (like GR) have.

**Comment by francispoulin** [comment]
I tried it and it still didn't finish after 4 hours.  Have you tried it?  If it runs faster for you then there is a problem with my setup.  But if it also doesn't finish for you, then I am doing something wrong.

**Comment by ChrisRackauckas** [comment]
No, it shouldn't take hours. It should take more like a minute or 2. I'll try running it again soon.

**Comment by ChrisRackauckas** [comment]
Yes I tried it. I just generated this:

![juliakttb1k](https://user-images.githubusercontent.com/1814174/31850824-92a11a90-b60e-11e7-937e-c793715dbde6.gif)

with

```julia
animate(sol,"/home/crackauc/Pictures",zlims=(0,10),cbar=false)
```

was fine. Have you made sure you're not just having problems with animations? Just run

```julia
using Plots, IterTools
itr = repeatedly(()->rand(10), 20)
animate(itr, ylims=(0,1), c=:red, fps=5)
```

**Comment by francispoulin** [comment]
Thanks for the reply.

First, I tried the example you have and it did work after I added IterTools, and it is a good test case.

Second, I decided to reduce the resolution to something very course and I did get an animation.  However, there is some odd behaviour.  

When I look at the size of sol1 (you seem to be saying sol?) I get that it is (32, 277).  I presume the 277 are the different time steps?  

Also, when I look at the animation I get that t is the x-axis and there are 32 lines being plotted.  I was expecting to get one single line moving, as it does in your nice example.  Do you know why it is plotting so many lines?

```

using DiffEqOperators, DifferentialEquations, Plots

N = 16
L = pi
Δx = 2*L/(N-1)
x = collect(-L : Δx : L);
u0 = -(x - 0.5).^2 + 1/12;
A = DerivativeOperator{Float64}(2,2,Δx,N,:Dirichlet,:Dirichlet;BC=(u0[1],u0[end]));

prob1 = ODEProblem(A, u0, (0.,10.));
sol1 = solve(prob1, dense=false, tstops=0:0.01:0.02);

animate(sol1,zlims=(0,10),cbar=false)

```

**Comment by ChrisRackauckas** [comment]
Oh wait, you're using the `ODESolution`'s animate. I was testing using the FEM tooling. For some reason I thought you were trying to run http://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqTutorials.jl/blob/master/ExtraFEMFeatures/Solving%20the%20Gierer-Meinhardt%20Equations.ipynb . 

I am so sorry.... I wondered...

Okay, this part just underwent a small revision anyways with DiffEqBase 2.0.0 changing the solution type to immutable. What it should be doing is only plotting up to `tslocation`, which when you iterate

```julia
for i in sol
  display(i)
end
```

you'll see that iterates up `1:length(sol)`. I checked to make sure the iterator is good, but I haven't the Plots.jl animation on that yet. When I get back to my desktop I'll run your example.

**Comment by francispoulin** [comment]
Thanks for catching that.  Ideally I want to use both the FE and FEM methods but I thought I would start with FE, since it is presumably easier.  

I tried what you suggested and I agree that we see arrays, which I presume are the correct ones.  I did the most naive thing I can imagine and that did not work.  

No rush to get to this as I imagine the fix will be pretty easy.

Thanks again.
```
for i in sol1
    plot(x, i)
  #display(i)
end
```

**Comment by ChrisRackauckas** [comment]
Sounds like the issue is that it's plotting only at `tslocation`, or transposing, or somehow not using the plot recipe.

**Comment by ChrisRackauckas** [comment]
![test](https://user-images.githubusercontent.com/1814174/31856701-8cf28b56-b67c-11e7-8607-9e322a0148b3.gif)

worked for me

**Comment by ChrisRackauckas** [comment]
Let me explain that a little bit. What `animate` does on an ODESolution (actually, anything except one of the special PDE solutions) is that it animates the generation of the time series using the plot recipe of the solution type. Generally for ODEs like the Lorenz attractor this makes sense. I assume that's not what you want here for drawing a PDE, so yeah, we'll have to use something different in this case. Let me play with it and find something out.

**Comment by ChrisRackauckas** [comment]
To make the PDE plot that you want you have to tell it x vs y:

```julia
plot(x,sol1[1])
```

Using that idea, I made it plot x vs y at every other timestep using the `@gif` macro:

```julia
@gif for i in 1:length(sol1)
    plot(x,sol1[i], xlims=(0,3), ylims=(-10,0), xlabel = "x", ylabel = "u(x)", title="Diffusion Equation Simulation",legend=false,lw=3)
end every 2
```

![juliamk6rj8](https://user-images.githubusercontent.com/1814174/31856748-c4747c14-b67d-11e7-8aed-9da3ccadc92f.gif)

But timesteps may not be what you want because they aren't evenly spaced. The solution is to either save an evenly spaced grid using `saveat` or loop through time and use the interpolation. I think this is clearer now?

**Comment by francispoulin** [comment]
Yes!  I am happy to say that this worked beautifully.  I also followed your advice using saveat and am now outputting the solution at regular time intervals, which makes for a better animation.

I will close this ticket but have one last question on this.  If I wanted to produce a Hovmoller plot, basically, a contour plot of the solution I thought I could try the following.  I realize that I might have the order of t and x mixed up but either order I try this doesn't work.   Could you tell me what the proper syntax is, preferably in Plots?


```

t = 0:0.1:10
contourf(x,t,sol1)
```

**Comment by ChrisRackauckas** [comment]
By default, `sol1[i,j]` has each column a time point, and so each row is a timeseries (and appropriate generalization if you use `u0` a matrix or tensor). So if you want a matrix with rows being the timeseries, you just convert:

```julia
contourf(x,t,convert(Array,sol1))
```

![plot](https://user-images.githubusercontent.com/1814174/31857372-d81d3aa8-b691-11e7-89d1-92111999577b.png)

But looking at the scale, I think you want columns to be timeseries, so you just transpose:

```julia
contourf(x,t,sol1')
```

![transposeplot](https://user-images.githubusercontent.com/1814174/31857373-d978b422-b691-11e7-9983-6bb74617a024.png)

**Comment by francispoulin** [comment]
Thank you!  That did the trick. 

After this lengthy but helpful discussion I have put together a notebook that puts this all together. Personally, I find it helpful to explain what the different pieces do.   If you think others might find this useful I would be happy to share this with people.  I couldn't attach it to this but if you wanted me to post it somewhere please let me know.

**Comment by ChrisRackauckas** [comment]
Can you submit it as a PR to this repo? It would likely be very helpful to others.

**Comment by francispoulin** [comment]
I will do this tomorrow.  But before i do this I wanted to add one more option.  Normally the diffusion equation is \kappa times the second derivative with respect to x.  What I would like to do is to allow for spatially variable diffusion rates, 

$$
\frac{\partial^2 u}{\partial t^2} = \frac{\partial}{\partial x} \left( \kappa(x) \frac{\partial u}{\partial t} \right)
$$

It shouldn't be difficult to do and when I set kappa 1 I should recover the same solution.  

However, when I plot the solution on a course grid I get that the values at the boundary actually change, and are not fixed.  I will think about this and see if I think this is a concern or not.  

More tomorrow.

**Comment by ChrisRackauckas** [comment]
What operators did you use? I think diffusion can be thought of as an upwind composed with a downwind.

**Comment by francispoulin** [comment]
I used the second derivative operator.  Since this is not an advection problem we don't want to use upwinding, so the example is using the correct operator (from what I understand).

If you look at the link below you will see a few stills and the boundary conditions at the left are not fixed, as they should be.  This is also apparent in the animation.  I

https://github.com/francispoulin/DiffEqOperators.jl/blob/master/docs/DiffusionEqTutorial.ipynb

When I output the value of the solution at the left end point I get numbers that clearly change.  Do you agree this needs to be fixed?  

After I get this going I am happy to make a more advanced notebook that has spatially variable diffusion.

 -13.1779
 -12.9645
 -12.4804
 -12.4055
 -12.7364
 -11.3679
 -12.2944
 -10.9973
 -12.5388
 -11.3032
 -10.0958
 -12.0742
 -10.9199
   ⋮     
 -12.7261
 -12.9549
 -12.5901
 -12.8167
 -13.0387
 -12.6829
 -12.9023
 -13.1183
 -12.7704
 -12.9838
 -12.6419
 -13.1779

**Comment by ChrisRackauckas** [comment]
yeah, something looks odd there. I think the way the Dirichlet BCs are implemented assumes the boundary is not in the array, and all values beyond the boundary are that constant. In that case, I think that the operator is doing something different than you meant it to because you have the boundaries as the last element? I agree that if this is the implementation that it is confusing and we should talk about / investigate this more in the DiffEqOperators.jl repo.

**Comment by francispoulin** [comment]
Okay, will move discussion there.
