### ISSUE TITLE
Example Heat Equation System Differing Diffusion Constants.ipynb is Broken

### ISSUE THREAD

**Issue by rcalxrc08** [JuliaDiffEq/DiffEqTutorials.jl#23]
Hi all,

I was trying to find out how the PDE solver of DifferentialEquations.jl works, but i am experiencing some problem.
I took the example from the notebook and i tried to run it as a script (https://pastebin.com/hbgkNAxe) but i am getting the following error:
`ERROR: LoadError: UndefVarError: parabolic_squaremesh not defined`

Probably the notebook has not been updated for the new versions of DifferentialEquations.jl.

**Comment by ChrisRackauckas** [comment]
That tutorial should be removed. We deprecated our FEM toolbox in the DifferentialEquations.jl v4.0 upgrade and instead are re-doing our "easy PDE" support. You can get this to work by pinning DiffEqPDEBase.jl back to v0.3.5.

**Comment by ChrisRackauckas** [comment]
This has been deleted.
