### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by OVGULIU** [JuliaDiffEq/DiffEqTutorials.jl#35]
Hi all,

how can  I remove the following bugs:

UndefVarError: sol not defined

UndefVarError: Yoshida6 not defined

UndefVarError: prob not defined

Thanks a lot in advance!

Best regards

**Comment by ChrisRackauckas** [comment]
what code did you run?

**Comment by OVGULIU** [comment]
e.g. Solving the Gierer-Meinhardt Equations.ipynb
...

**Comment by ChrisRackauckas** [comment]
oh, that one is old and should just be removed. The FEM toolbox it uses no longer exists.

**Comment by OVGULIU** [comment]
or another question: which benchmarks can we use now....

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl ?

**Comment by OVGULIU** [comment]
Nice, thanks for your research support!

Best regards

**Comment by ChrisRackauckas** [comment]
No problem.
