### ISSUE TITLE
Weave.jl issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqTutorials.jl#37]
Current Weave.jl issues:

- [x] Unitful tutorial breaks Weave.jl mpastell/Weave.jl#175
- [x] Measurements.jl tutorial gives an issue with Weave.jl's `latex` function
- [x] Weave.jl's notebook output is currently broken. For this package we simply disabled those outputs for now.
- [x] HTML does not render TeX: https://github.com/mpastell/Weave.jl/issues/178

**Comment by ChrisRackauckas** [comment]
For the first, it's:

```julia
using DiffEqTutorials
DiffEqTutorials.weave_file(".","type_handling/unitful.jmd")
```

and the second is

```julia
using DiffEqTutorials
DiffEqTutorials.weave_file(".","type_handling/uncertainties.jmd")
```

**Comment by ChrisRackauckas** [comment]
@mpastell this is where we are tracking the Weave.jl issues for our tutorials. We just updated everything and moved from Jupyter notebooks to a Weave.jl-based system and did run into a few rough edges.

**Comment by ChrisRackauckas** [comment]
The notebook output is "fixed", but it doesn't render nicely quite yet.

**Comment by mpastell** [comment]
Great that you're using Weave for this! I don't have a lot of time work on Weave right now, but I'll do my best to help you sort out these issues.

**Comment by ChrisRackauckas** [comment]
Thanks for helping! It's definitely putting Weave through a big test and it's mostly passing. I think the last thing is trying to find out what the issue is in the `latex` function when you run:

```julia
using DiffEqTutorials
DiffEqTutorials.weave_file("type_handling","unitful.jmd")
```

**Comment by mpastell** [comment]
I've fixed the header issue in notebooks and will look into the latex issue next.

**Comment by mpastell** [comment]
The LaTex issue is caused by https://github.com/mpastell/Weave.jl/issues/181 . You can check for latex errors more easily using the `md2tex` format and running xelatex on the resulting .tex file, this is also what the `m2pdf` format does.
