### ISSUE TITLE
Add a Project/Manifest

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqTutorials.jl#43]
@YingboMa is there a way to reliably grab/use a Project/Manifest pair kept in the repo here?

**Comment by devmotion** [comment]
I don't know whether this answers your questions, but at the moment I use
```julia
using Pkg; Pkg.activate(@__DIR__); Pkg.instantiate()
```
at the top of my scripts and notebooks that I want to be reproducible and include both the Project and Manifest file in my git repository. I'm not sure though whether that's the best way to ensure reproducibility, there's a longer discussion about notebooks and Manifest files here: https://github.com/JuliaLang/IJulia.jl/issues/673

**Comment by arnavs** [comment]
@ChrisRackauckas using git-hosted TOML is exactly the use case of `QuantEcon/InstantiateFromURL.jl`

**Comment by arnavs** [comment]
Note, though, that while we don't consume git API calls, we do download the whole tarball/7zip file. Basically, it's best for dedicated TOML repos, like `QuantEcon/QuantEconLecturePackages`, `QuantEcon/QuantEconLectureAllPackages`, etc.

The good news though is that the version/tag information is cached, so you can use those features.
