### ISSUE TITLE
html files not rendering in Github

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqTutorials.jl#45]
The ones I looked at seem to just be rendering as raw text in Github. Is this what's supposed to happen? With the notebooks no longer having figures it would be nice if the html files were rendered so we could link to them from different places.

**Comment by isaacsas** [comment]
Or maybe they are now only supposed to be linked through `juliadiffeq.org` instead of through the repository? The links in the README seem to render properly but not directly clicking into the html folder of the repository.

**Comment by ChrisRackauckas** [comment]
They are rendered via Github Pages. The rendered pages are the ones that should be linked to.

**Comment by isaacsas** [comment]
Got it, thanks for the clarification.
