### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqTutorials.jl#46]
At least for me, the package could not just be added as described in the README. I was initially getting an error about:
```
ERROR: Unsatisfiable requirements detected for package UnitfulPlots [2a06ce6d]:
 UnitfulPlots [2a06ce6d] log:
 ├─UnitfulPlots [2a06ce6d] has no known versions!
 └─restricted to versions * by DiffEqTutorials [6d1b261a] — no versions left
   └─DiffEqTutorials [6d1b261a] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─DiffEqTutorials [6d1b261a] is fixed to version 0.1.0
```
It seems `UnitfulPlots` is not in the registry, so one has to explicitly add it from the Github repository. This might be worth mentioning as I imagine tutorials users may not be able to figure out these types of issues on their own...

**Comment by ChrisRackauckas** [comment]
I tried this on my laptop last night and got the same thing. Seems like we should just get it registered...

**Comment by isaacsas** [comment]
It might also be worth mentioning something about installing CUDA first -- I don't have it installed and got a number of errors when installing about how it wouldn't work. (Unlike UnitfulPlots it doesn't seem to break installation...)

**Comment by ChrisRackauckas** [comment]
Yeah, I wonder if there's a way to do conditional dependencies in some sense.

**Comment by dkarrasch** [comment]
@ChrisRackauckas Is [Requires.jl](https://github.com/MikeInnes/Requires.jl) what you're looking for?

**Comment by ChrisRackauckas** [comment]
No, that's for packages.

**Comment by ChrisRackauckas** [comment]
I removed UnitfulPlots and am just doing without it. Fingers crossed we're all good.
