### ISSUE TITLE
footer in scripts

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqTutorials.jl#48]
At the end of scripts the following code gets added, but seems not to be run-able:
```
using DiffEqTutorials
DiffEqTutorials.tutorial_footer(WEAVE_ARGS[:folder],WEAVE_ARGS[:file])
```
Should this be removed from `.jl` files?

**Comment by ChrisRackauckas** [comment]
Yes, it probably should. I'm not sure if it's possible from Weave though since those are generated by a tangle, and I'm not sure there's a "don't tangle" argument for a block. @mpastell

**Comment by isaacsas** [comment]
A second issue is that I get an error about trying to display nothing in the generated html file:
```
ERROR: ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output instead.
```

This is using the corrected footer:
~~~
```julia echo=false; skip="notebook"
using DiffEqTutorials
DiffEqTutorials.tutorial_footer(WEAVE_ARGS[:folder],WEAVE_ARGS[:file])
```
~~~

**Comment by ChrisRackauckas** [comment]
On latest master?

https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/src/DiffEqTutorials.jl#L94

This was added to stop the nothing print issue.

**Comment by isaacsas** [comment]
Darn, sorry about that -- I missed that master had been updated... That fixes it.

**Comment by mpastell** [comment]
> Yes, it probably should. I'm not sure if it's possible from Weave though since those are generated by a tangle, and I'm not sure there's a "don't tangle" argument for a block. @mpastell

There is, you can use `tangle=false` chunk option http://weavejl.mpastell.com/stable/chunk_options/#Options-for-code-1
