### ISSUE TITLE
notebook title and authors placed after initial text

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqTutorials.jl#49]
See [here](https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/notebook/models/classical_physics.ipynb).

The markdown file has
```
---
title: Classical Physics Models
author: Yingbo Ma, Chris Rackauckas
---
```

as the beginning text, but in the notebook it is appearing after the initial markdown text. Contrast this to the html file [here](http://juliadiffeq.org/DiffEqTutorials.jl/html/models/classical_physics.html).

**Comment by ChrisRackauckas** [comment]
I think this is fixed in the next Weave.jl release.

**Comment by isaacsas** [comment]
Fixed as you say.
