### ISSUE TITLE
Update Dynamical ODE Tutorials

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqTutorials.jl#6]
Now that there's a "set interface" which is much better for handling these, we should convert the tutorials in here over to using that. So `SecondOrderODEProblem` and `DynamicalODEProblem` instead of defining by tuples (though it does lower to the same thing, except using the `DynamicalODEProblem` so that first-order ODE methods work via an automatic transformation). 

@YingboMa

**Comment by YingboMa** [comment]
#7
