### ISSUE TITLE
Notebooks displayed in Jupyter are not ordered

### ISSUE THREAD

**Issue by goggle** [JuliaDiffEq/DiffEqTutorials.jl#60]
The notebooks in the Jupyter overview are ordered alphabetically by default. It looks like this:
![image](https://user-images.githubusercontent.com/1856425/60118849-75870580-977d-11e9-9b47-9611ef196555.png)
But the README suggests to work through the notebooks in a specific order:

1. Introduction to DifferentialEquations.jl through ODEs
2. Detecting Stiffness and Choosing an ODE Algorithm
3. etc.

This could be solved by renaming the notebooks, e.g. `01-ode_introduction.ipynb` instead of `ode_introduction.ipynb`

**Comment by ChrisRackauckas** [comment]
Thanks for pointing this out. Yes, not difficult to fix but someone has to go in and do it.

**Comment by goggle** [comment]
I can have a look at this.
Should I replace the files in `html/`, `pdf/` and `script/` with the new Weave builds or just rename the existing files in these folders?
I will replace the notebooks with the new Weave builds, because it fixes #49 which was closed for some reason.

**Comment by ChrisRackauckas** [comment]
Replace it in the tutorials folder and then rebuild, otherwise all those changes will get overwritten next rebuild.

**Comment by goggle** [comment]
Closed by #62.
