### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by goggle** [JuliaDiffEq/DiffEqTutorials.jl#64]
When I did the rebuild of most of the tutorials some days ago, I've noticed that I had to install several packages by hand to succeed. I wrote them down:

- `DiffeqBiological`
- `PyPlot`
- `Latexify`
- `ModelingToolkit`
- `NLsolve`
- `Distributions`
- `StatsPlots`
- `Cairo`

Should these packages be added to `Project.toml`?
If so, does this need be done by hand? How do I get the UUID of such a package?

**Comment by ChrisRackauckas** [comment]
`]activate DiffEqTutorials
add PackageName`
