### ISSUE TITLE
small typo in Chemical Langevin Equation

### ISSUE THREAD

**Issue by chvandorp** [JuliaDiffEq/DiffEqTutorials.jl#76]
Hi Samuel, thanks for the nice tutorial! Just wanted to point out a small mistake in the text of DiffEqBiological Tutorial I: Introduction. In the CLE example you define a reaction network
```
bdp = @reaction_network begin
  c₁, X --> 2X
  c₂, X --> 0
  c₃, 0 --> X
end c₁ c₂ c₃
p = (1.0,2.0,50.)
u₀ = [5.]
tspan = (0.,4.);
```
and then mention that the corresponding SDE is 
```dX_t = \left(c_1 X - c_2 X + c_3 \right) dt + \left( \sqrt{c_1 X} - \sqrt{c_2 X} + \sqrt{c_3} \right)dW_t```
I think that should be either
```dX_t = \left(c_1 X - c_2 X + c_3 \right) dt + \sqrt{c_1 X} dW^1_t - \sqrt{c_2 X} dW^2_t + \sqrt{c_3}dW^3_t```
where `W_t` is a 3-dimensional Wiener process, or perhaps
```dX_t = \left(c_1 X - c_2 X + c_3 \right) dt + \sqrt{c_1 X + c_2 X + c_3}dW_t```
with a 1-dimensional Wiener process. But I reckon the implementation uses the 3-dim process.

**Comment by ChrisRackauckas** [comment]
It's the 3-dimensional process. We should probably make that explicit. Nice catch.

**Comment by isaacsas** [comment]
Yes, that’s definitely a mistake. I’ll update it. Thanks!

**Comment by isaacsas** [comment]
@ChrisRackauckas This can be closed now.
