### ISSUE TITLE
How to stop a integration before end time

### ISSUE THREAD

**Issue by kuro26** [JuliaDiffEq/DiffEqTutorials.jl#77]
Looking for methods to stop integration at events.

**Comment by ChrisRackauckas** [comment]
http://docs.juliadiffeq.org/latest/features/callback_functions.html#Example-2:-Terminating-an-Integration-1

**Comment by ChrisRackauckas** [comment]
Let me know if you need anything else.

**Comment by kuro26** [comment]
Thank you for answering, it is of great help to me!
