### ISSUE TITLE
Error When Following Heat Eqn. Tutorial

### ISSUE THREAD

**Issue by nick4110** [JuliaDiffEq/DiffEqTutorials.jl#80]
Hello,

I am using DifferentialEquations.jl version 6.8.0 and attempting to follow the tutorial at [https://docs.juliadiffeq.org/v1.10.1/tutorials/femheat_example.html](https://docs.juliadiffeq.org/v1.10.1/tutorials/femheat_example.html)
 and I have an error when running the line `mesh = parabolic_squaremesh([0 1 0 1],dx,dt,tspan,:neumann)`

I get the message "UndefVarError: parabolic_squaremesh not defined." When I try to update DiffEqPDEBase I get the following message:

`ERROR: Unsatisfiable requirements detected for package DiffEqBase [2b5f629d]:
 DiffEqBase [2b5f629d] log:
 ├─possible versions are: [3.13.2-3.13.3, 4.0.0-4.0.1, 4.1.0, 4.2.0, 4.3.0-4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.9.0, 4.10.0-4.10.1, 4.11.0-4.11.1, 4.12.0, 4.13.0, 4.14.0-4.14.1, 4.15.0, 4.16.0, 4.17.0, 4.18.0, 4.19.0, 4.20.0-4.20.3, 4.21.0, 4.21.2-4.21.3, 4.22.0-4.22.2, 4.23.0, 4.23.2-4.23.4, 4.24.0-4.24.3, 4.25.0-4.25.1, 4.26.0-4.26.3, 4.27.0-4.27.1, 4.28.0-4.28.1, 4.29.0-4.29.2, 4.30.0-4.30.2, 4.31.0-4.31.2, 4.32.0, 5.0.0-5.0.1, 5.1.0, 5.2.0-5.2.3, 5.3.0-5.3.2, 5.4.0-5.4.1, 5.5.0-5.5.2, 5.6.0-5.6.4, 5.7.0, 5.8.0-5.8.1, 5.9.0, 5.10.0-5.10.3, 5.11.0-5.11.1, 5.12.0, 5.13.0, 5.14.0-5.14.2, 5.15.0, 5.16.0-5.16.5, 5.17.0-5.17.1, 5.18.0, 5.19.0, 5.20.0-5.20.1, 6.0.0, 6.1.0, 6.2.0-6.2.4, 6.3.0-6.3.6, 6.4.0-6.4.2] or uninstalled
 ├─restricted by compatibility requirements with DifferentialEquations [0c46a032] to versions: [6.2.2-6.2.4, 6.3.0-6.3.6, 6.4.0-6.4.2]
 │ └─DifferentialEquations [0c46a032] log:
 │   ├─possible versions are: [5.0.0, 5.1.0, 5.2.0-5.2.1, 5.3.0-5.3.1, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.6.0, 6.7.0, 6.8.0] or uninstalled
 │   └─restricted to versions 6.8.0 by an explicit requirement, leaving only versions 6.8.0
 └─restricted by compatibility requirements with DiffEqPDEBase [34035eb4] to versions: [3.13.2-3.13.3, 4.0.0-4.0.1, 4.1.0, 4.2.0, 4.3.0-4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.9.0, 4.10.0-4.10.1, 4.11.0-4.11.1, 4.12.0, 4.13.0, 4.14.0-4.14.1, 4.15.0, 4.16.0, 4.17.0, 4.18.0, 4.19.0, 4.20.0-4.20.3, 4.21.0, 4.21.2-4.21.3, 4.22.0-4.22.2, 4.23.0, 4.23.2-4.23.4, 4.24.0-4.24.3, 4.25.0-4.25.1, 4.26.0-4.26.3, 4.27.0-4.27.1, 4.28.0-4.28.1, 4.29.0-4.29.2, 4.30.0-4.30.2, 4.31.0-4.31.2, 4.32.0, 5.0.0-5.0.1, 5.1.0, 5.2.0-5.2.3, 5.3.0-5.3.2, 5.4.0-5.4.1, 5.5.0-5.5.2, 5.6.0-5.6.4, 5.7.0, 5.8.0-5.8.1, 5.9.0, 5.10.0-5.10.3, 5.11.0-5.11.1, 5.12.0, 5.13.0, 5.14.0-5.14.2, 5.15.0, 5.16.0-5.16.5, 5.17.0-5.17.1, 5.18.0, 5.19.0, 5.20.0-5.20.1] — no versions left
   └─DiffEqPDEBase [34035eb4] log:
     ├─possible versions are: 0.4.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.4.0
`

Is there a better way to call the meshing function, or is there some way to update the required dependency DiffEqPDEBase?

**Comment by ChrisRackauckas** [comment]
That functionality hasn't existed since DiffEq 2.0. Please look to JuliaFEM or FEniCS.jl for FEM functionality.

**Comment by ChrisRackauckas** [comment]
Somehow you found the v1.10 docs.
